apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metrics-app.fullname" . }}
  labels:
    app: {{ include "metrics-app.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "metrics-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "metrics-app.name" . }}
    spec:
      containers:
        - name: metrics-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "metrics-app.fullname" . }}-secret
                  key: password
